from __future__ import annotations

import argparse
import base64
from pathlib import Path
import zlib


ROOT = Path(__file__).resolve().parents[1]
KERNEL_DIR = ROOT / "notebooks" / "jahyee__nemotron-trace-logprob-audit"
DEFAULT_LAUNCHER = KERNEL_DIR / "nemotron-trace-logprob-audit.py"
DEFAULT_HELPER = KERNEL_DIR / "trace_logprob_audit.py"
DEFAULT_MANIFEST = KERNEL_DIR / "trace_manifest_first_gpu_audit_slim64.jsonl"
DEFAULT_OUTPUT = KERNEL_DIR / "nemotron-trace-logprob-audit-bundled.py"
HELPER_PLACEHOLDER = "EMBEDDED_TRACE_LOGPROB_AUDIT_SOURCE: str | None = None"
MANIFEST_PLACEHOLDER = "EMBEDDED_TRACE_MANIFEST_JSONL: str | None = None"


def main() -> None:
    parser = argparse.ArgumentParser(description="Bundle trace_logprob_audit.py into the Kaggle script code_file.")
    parser.add_argument("--launcher", type=Path, default=DEFAULT_LAUNCHER)
    parser.add_argument("--helper", type=Path, default=DEFAULT_HELPER)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    launcher = args.launcher.read_text(encoding="utf-8")
    helper = args.helper.read_text(encoding="utf-8")
    manifest = args.manifest.read_text(encoding="utf-8") if args.manifest.exists() else None
    if HELPER_PLACEHOLDER not in launcher:
        raise RuntimeError(f"Could not find helper placeholder in {args.launcher}")
    if manifest is not None and MANIFEST_PLACEHOLDER not in launcher:
        raise RuntimeError(f"Could not find manifest placeholder in {args.launcher}")

    bundled = launcher.replace(
        HELPER_PLACEHOLDER,
        f"EMBEDDED_TRACE_LOGPROB_AUDIT_SOURCE: str | None = {helper!r}",
        1,
    )
    if manifest is not None:
        compressed_manifest = base64.b64encode(
            zlib.compress(manifest.encode("utf-8"), level=9)
        ).decode("ascii")
        manifest_expr = (
            "__import__('zlib').decompress("
            f"__import__('base64').b64decode({compressed_manifest!r})"
            ").decode('utf-8')"
        )
        bundled = bundled.replace(
            MANIFEST_PLACEHOLDER,
            f"EMBEDDED_TRACE_MANIFEST_JSONL: str | None = {manifest_expr}",
            1,
        )
    banner = (
        "# Generated by scripts/bundle_trace_logprob_audit_kernel.py.\n"
        "# Edit nemotron-trace-logprob-audit.py or trace_logprob_audit.py, then regenerate.\n\n"
    )
    args.output.write_text(banner + bundled, encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
